name: Run PetClinic with Contrast

on: [push]

jobs:
  run-petclinic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin

    - name: Download Contrast Agent
      run: wget -q -O contrast.jar https://download.java.contrastsecurity.com/latest

    - name: Set up Contrast environment variables
      run: |
        echo "CONTRAST__API__URL=${{ secrets.CONTRAST_API_URL }}" >> $GITHUB_ENV
        echo "CONTRAST__API__API_KEY==${{ secrets.CONTRAST_API_KEY }}" >> $GITHUB_ENV
        echo "CONTRAST__API__SERVICE_KEY==${{ secrets.CONTRAST_API_SERVICE_KEY }}" >> $GITHUB_ENV
        echo "CONTRAST__API__USER_NAME==${{ secrets.CONTRAST_API_USERNAME }}" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    - name: Install Playwright dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libgbm-dev libxkbcommon-x11-0 libgtk-3-0 libasound2

    - name: Install Playwright
      run: npx playwright install

    - name: Verify Playwright installation
      run: npx playwright --version

    - name: Run PetClinic
      run: |
        nohup java -javaagent:contrast.jar -Dcontrast.application_name=PetClinic -Dcontrast.application.session_metadata="branchName=${{ github.ref }},commitHash=${{ github.sha }},repository=${{ github.repository }}" -jar spring-petclinic-1.5.1.jar &

    - name: Exercise PetClinic
      run: |
        sleep 30 # Wait for WebGoat to start
        npx playwright test
